language: objective-c
osx_image: xcode11.3

rvm: 2.4.3
before_install:
    - gem install bundler -v 2.0.2
    - bundle install --path vendor/bundle
    - bundle exec pod setup > /dev/null    #/dev/null to prevent long logs

install:
    - bundle exec pod install --repo-update --verbose

podfile: Podfile
xcode_workspace: TravelpayoutsTravelApp.xcworkspace
xcode_scheme: TravelpayoutsTravelApp
xcode_sdk:
    - iphonesimulator

script:
   - xcodebuild -workspace TravelpayoutsTravelApp.xcworkspace -scheme TravelpayoutsTravelApp -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.3,name=iPhone 8" COMPILER_INDEX_STORE_ENABLE=NO build test | bundle exec xcpretty
